#if !defined(AFX_TCATDEFINT_H__2A12DFE3_B911_4A97_BCFC_590E28ED3316__INCLUDED_)
#define AFX_TCATDEFINT_H__2A12DFE3_B911_4A97_BCFC_590E28ED3316__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// TCatDefInt.h : header file
//
/*
This file is part of LM Report Asistent.

Authors: Jan Dedek, Jan Kodym, Martin Chrz, Iva Bartunkova

LM Report Asistent is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

LM Report Asistent is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with LM Report Asistent; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/
#include "afxdb.h"
/////////////////////////////////////////////////////////////////////////////
// TCatDefInt recordset

/**
 * This class was designed to retrieve the details for categories of type interval.
 *
 * @author Generated by VS.
 */
class TCatDefInt : public CRecordset
{
public:
	TCatDefInt(CDatabase* pDatabase = NULL);
	DECLARE_DYNAMIC(TCatDefInt)

// Field/Param Data
	//{{AFX_FIELD(TCatDefInt, CRecordset)
	long	m_IntervalID;
	long	m_CategoryID;
	long	m_FromValueID;
	long	m_ToValueID;
	long	m_LeftBracketTypeID;
	long	m_RightBracketTypeID;
	long	m_ValueID;
	long	m_ValueSubTypeID;
	long	m_ValueLong;
	double	m_ValueFloat;
	CString	m_ValueString;
	BOOL	m_ValueBool;
	CTime	m_ValueDate;
	long	m_InfinityTypeID;
	BOOL	m_IsNULL;
	long	m_BracketTypeID;
	CString	m_Name;
	CString	m_ShortName;
	long	m_Ord;
	CString	m_LeftBracket;
	CString	m_RightBracket;
	CString	m_Notice;
	long	m_ValueSubTypeID2;
	CString	m_Name2;
	CString	m_ShortName2;
	BOOL	m_Cardinal;
	long	m_Ord2;
	CString	m_Notice2;
	//}}AFX_FIELD


// Overrides
	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(TCatDefInt)
	public:
	virtual CString GetDefaultSQL();    // Default SQL for Recordset
	virtual void DoFieldExchange(CFieldExchange* pFX);  // RFX support
	//}}AFX_VIRTUAL

// Implementation
#ifdef _DEBUG
	virtual void AssertValid() const;
	virtual void Dump(CDumpContext& dc) const;
#endif
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TCATDEFINT_H__2A12DFE3_B911_4A97_BCFC_590E28ED3316__INCLUDED_)
