// ReportAsistent.idl : IDL source for ReportAsistent.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (ReportAsistent.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
[
	uuid(43476C69-1127-4317-8065-32DD02CE7AD3),
	version(1.0),
	helpstring("ReportAsistent 1.0 Type Library")
]
library REPORTASISTENTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
	importlib("C:\Program Files\Microsoft Office\Office\MSWORD9.OLB");
	importlib("C:\Program Files\Microsoft Office\Office\GRAPH9.OLB");

	typedef enum {elTable, elGraph, elText, /*elParagraph, - bude uvnitr elText*/ elCompound, elNothing} ElementTypeEnum;

	[
		object,
		uuid(F5EBE35B-1ABC-4F40-81AE-0D5D692BFDCC),
		dual,
		helpstring("IInsertElement Interface"),
		pointer_default(unique)
	]
	interface IInsertElement : IDispatch
	{
		[propget, id(1), helpstring("property elementType")] HRESULT elementType([out, retval] ElementTypeEnum *pVal);
	};
	[
		uuid(399FF362-6189-48A0-90A3-DC4AE0AF0E41),
		helpstring("InsertElement Class")
	]
	coclass InsertElement
	{
		[default] interface IInsertElement;
	};
	[
		object,
		uuid(528746CB-465B-4DC2-9758-54EF90E93253),
		dual,
		helpstring("IMainObject Interface"),
		pointer_default(unique)
	]
	interface IMainObject : IDispatch
	{
		[propget, id(1), helpstring("property GetNextInsertElement")] HRESULT GetNextInsertElement([out, retval] InsertElement* *pVal);
	};
	[
		object,
		uuid(F6EE1307-8A05-4191-B301-BBA75309C5F9),
		dual,
		helpstring("IElementGraph Interface"),
		pointer_default(unique)
	]
	interface IElementGraph : IInsertElement
	{
		[propget, id(2), helpstring("property Cells")] HRESULT Cells(long x, long y, [out, retval] VARIANT *pVal);
		[propget, id(3), helpstring("property Cells_dx")] HRESULT Cells_dx([out, retval] long *pVal);
		[propget, id(4), helpstring("property Cells_dy")] HRESULT Cells_dy([out, retval] long *pVal);
		[propget, id(5), helpstring("property graphType")] HRESULT graphType([out, retval] enum XlChartType *pVal);
	};
	[
		object,
		uuid(D30237AD-74C9-4550-B1BB-AFE8B3954CD2),
		dual,
		helpstring("ITableCell Interface"),
		pointer_default(unique)
	]
	interface ITableCell : IDispatch
	{
		[propget, id(1), helpstring("property Content")] HRESULT Content([out, retval] InsertElement * *pVal);
		[propget, id(2), helpstring("property BackgroundPatternColor")] HRESULT BackgroundPatternColor([out, retval] enum WdColor *pVal);
	};
	[
		uuid(08C96A1F-578C-4687-8E17-BF4B1DA124B7),
		helpstring("TableCell Class")
	]
	coclass TableCell
	{
		[default] interface ITableCell;
	};
	[
		object,
		uuid(F722E34C-CC0B-4F9E-A5DD-C24BCB9476BC),
		dual,
		helpstring("IElementTable Interface"),
		pointer_default(unique)
	]
	interface IElementTable : IInsertElement
	{
		[propget, id(2), helpstring("property Cells_dx")] HRESULT Cells_dx([out, retval] long *pVal);
		[propget, id(3), helpstring("property Cells_dy")] HRESULT Cells_dy([out, retval] long *pVal);
		[propget, id(4), helpstring("property Cells")] HRESULT Cells(long x, long y, [out, retval] TableCell * *pVal);
		[propget, id(5), helpstring("property AutoFitBehavior")] HRESULT AutoFitBehavior([out, retval] enum WdAutoFitBehavior *pVal);
		[propget, id(6), helpstring("property RowAlignment")] HRESULT RowAlignment([out, retval] enum WdRowAlignment *pVal);
	};
	[
		object,
		uuid(9AFC803C-9447-468A-86D8-2B7F68DDFB4F),
		dual,
		helpstring("IElementText Interface"),
		pointer_default(unique)
	]
	interface IElementText : IInsertElement
	{
		[propget, id(2), helpstring("property Text")] HRESULT Text([out, retval] BSTR *pVal);
		[propget, id(3), helpstring("property NewParagraph")] HRESULT NewParagraph([out, retval] BOOL *pVal);
		[propget, id(4), helpstring("property Style")] HRESULT Style([out, retval] VARIANT *pVal);
	};
	[
		object,
		uuid(C299196A-1F94-4205-BE86-D7DD70B4EC7E),
		dual,
		helpstring("IElementCompound Interface"),
		pointer_default(unique)
	]
	interface IElementCompound : IInsertElement
	{
		[propget, id(2), helpstring("property GetNextInsertElement")] HRESULT GetNextInsertElement([out, retval] InsertElement * *pVal);
		[propget, id(3), helpstring("property continueInserting")] HRESULT continueInserting([out, retval] BOOL *pVal);
	};


	[
		uuid(6775171E-053A-4C35-842D-EED56C4B3531),
		helpstring("MainObject Class")
	]
	coclass MainObject
	{
		[default] interface IMainObject;
	};
	[
		uuid(286AE5CF-B993-4B21-A82D-E1A376176EE1),
		helpstring("ElementGraph Class")
	]
	coclass ElementGraph
	{
		[default] interface IElementGraph;
	};
	[
		uuid(62B1DDCB-BF46-4608-BA97-587BA31D9111),
		helpstring("ElementTable Class")
	]
	coclass ElementTable
	{
		[default] interface IElementTable;
	};
	[
		uuid(15D3EE0E-5C5C-4C0B-8FF3-F3574DA11738),
		helpstring("ElementText Class")
	]
	coclass ElementText
	{
		[default] interface IElementText;
	};
	[
		uuid(9E41D594-1F37-414D-94BB-D4F58975F8B1),
		helpstring("ElementCompound Class")
	]
	coclass ElementCompound
	{
		[default] interface IElementCompound;
	};
};
