//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ReportAsistent.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_REPORTTYPE                  129
#define IDD_DIALOGTEXT                  130
#define IDB_BMTREEFIRST                 134
#define IDB_CHAPTERICO                  135
#define IDB_PARAGRAPHICO                136
#define IDB_REPORTICO                   137
#define IDB_TABLEICO                    138
#define IDB_TEXTICO                     139
#define IDB_UNKNOWNICO                  140
#define IDB_4FTHYPOTEZAICO              141
#define IDB_BMTREELAST                  142
#define IDD_SIMPLE_FILTER_DIALOG        143
#define IDD_GENERATE_DIALOG             144
#define IDD_SOURCES_DIALOG              145
#define IDD_ECTIVE_ELEMENT_DIALOG       147
#define IDD_ACTIVE_ELEMENT_DIALOG       147
#define IDD_TRANSFORMATIONS_DIALOG      148
#define IDB_TRANSFORMATIONS_LOGO        150
#define IDD_ATTRIBUTE_LINK_DIALOG       151
#define IDD_ATTRIBUTE_LINK_TABLE_DIALOG 152
#define IDD_DIALOG_PARAGRAPH            153
#define IDD_DIALOG_CHAPTER              154
#define IDD_PROPERTY_EDITOR             155
#define IDB_INCLUDEICO                  157
#define IDB_ATTRLINKTABLEICO            158
#define IDB_ATTRLINKICO                 159
#define IDR_SKELETON_DTD                160
#define IDR_VISUALIZATION_OPTIONS_DTD   162
#define IDD_WAIT_DIALOG                 163
#define IDR_SKELETON_DTD1               163
#define IDR_STATIC_ELEMENTS             163
#define IDD_OPTIONS_DIALOG              164
#define IDD_DIALOG_REPORT               166
#define IDD_COMPLEX_FILTER_DIALOG       168
#define IDD_INCLUDE_DIALOG              170
#define IDD_FILTER_AND_CONFIG_DIALOG    171
#define IDD_AEL_CONFIG_DIALOG           172
#define IDC_TREE1                       1000
#define IDC_FILTER_LIST                 1000
#define IDC_SCROLLBAR1                  1000
#define IDC_EDIT1                       1001
#define IDC_DIALTEXT_EDIT               1001
#define IDC_STATIC1                     1001
#define IDC_TOPN_EDIT                   1001
#define IDC_TREE_ITEM_HEIGHT            1001
#define IDC_GENERATE_BUTTON             1002
#define IDC_EDIT3                       1002
#define IDC_DATA_SOURCE_COMBO           1003
#define IDC_ERROR_TEXT                  1003
#define IDC_PLUGINS_COMBO               1004
#define IDC_ADD_SOURCE_BUTTON           1006
#define IDC_SOURCES_LIST                1007
#define IDC_CONNECT_BUTTON              1008
#define IDC_OPEN_BUTTON                 1008
#define IDC_DISCONNECT_BUTTON           1009
#define IDC_CLOSE_BUTTON                1009
#define IDC_TAB1                        1009
#define IDC_REMOVE_BUTTON               1010
#define IDC_APPLY_BUTTON                1010
#define IDC_RENAME_BUTTON               1011
#define IDC_SET_DEFAULT_BUTTON          1012
#define IDC_SWITCH_BUTTON               1015
#define IDC_SUPPORTED_TRANSF_LIST       1016
#define IDC_SELECTED_TRANSFS_LIST       1017
#define IDC_ADD_BUTTON                  1018
#define IDC_SUPPORTED_TRANSF_LIST2      1019
#define IDC_MOVE_UP_BUTTON              1020
#define IDC_MOVE_DOWN_BUTTON            1021
#define IDC_TARGET_COMBO                1021
#define IDC_ATTRIBUTES_LIST             1022
#define IDC_REFRESH_BUTTON              1023
#define IDC_ATTRIBUTES_LIST2            1023
#define IDC_VALUES_LIST                 1023
#define IDC_LIST1                       1024
#define IDC_CAPTIONS_LIST               1024
#define IDC_STYLES_COMBO                1024
#define IDC_RESULT_LIST                 1024
#define IDC_MOVE_DOWN_BUTTON2           1025
#define IDC_STYLES_REFRESH_BUTTON       1025
#define IDC_LIST2                       1025
#define IDC_FILTERS_LIST                1025
#define IDC_EDIT_CAPTION_BUTTON         1026
#define IDC_DIALTEXT_IDEDIT             1027
#define IDC_STYLE_COMBO                 1027
#define IDC_DIALPARAGRAPH_IDEDIT        1028
#define IDC_DIALCHAPTER_IDEDIT          1029
#define IDC_DIALCHAPTER_TITLEEDIT       1030
#define IDC_ADD_ATTR_LINK_TABLE_BUTTON  1031
#define IDC_CONFIGURE_ATTR_LINK_TABLE_BUTTON 1032
#define IDC_CONFIGURE_BUTTON            1032
#define IDC_WAIT_ANIMATION              1034
#define IDC_CZECH_RADIO                 1035
#define IDC_ENGLISH_RADIO               1036
#define IDC_EXIT_BUTTON                 1037
#define IDC_REASON_TEXT                 1038
#define IDC_RESUME_APP_BUTTON           1039
#define IDC_KILL_THREAD_BUTTON          1040
#define IDC_DIALREPORT_IDEDIT           1040
#define IDC_DIALREPORT_TITLEEDIT        1041
#define IDC_DIALREPORT_SUBTITLEEDIT     1042
#define IDC_ASCENDING_RADIO             1042
#define IDC_DIALREPORT_AUTHOREDIT       1043
#define IDC_DESCENDING_RADIO            1043
#define IDC_NUMERIC_SORT_CHECK          1044
#define IDC_BUTTON2                     1046
#define IDC_BUTTON3                     1047
#define IDC_BUTTON4                     1048
#define IDC_TRESHOLD_RADIO              1049
#define IDC_FIXED_VAL_RADIO             1050
#define IDC_TOP_N_VAL_RADIO             1051
#define IDC_EDIT2                       1052
#define IDC_TRESHOLD_EDIT               1052
#define IDC_TREE_ITEM_INDENT            1052
#define IDC_ATTRLINK_ID_EDIT            1053
#define IDC_ATTRLINKTABLE_ID_EDIT       1054
#define IDC_INCLUDE_FILENAME_EDIT       1055
#define IDC_BROWSE_BUTTON               1056
#define IDC_INCLUDE_ID_EDIT             1057
#define IDC_BUTTON1                     1058
#define IDC_REFRESH_RESULTS_BUTTON      1058
#define IDC_ADD_FILTER_BUTTON           1060
#define IDC_ADD_FILTER_BUTTON2          1061
#define IDC_SIMPLEFILTER_ID_EDIT        1061
#define IDC_CONFIGURE_FILTER_BUTTON     1061
#define IDC_CF_ID_EDIT                  1062
#define IDC_TOPN_SPIN                   1062
#define IDC_ID_EDIT                     1062
#define IDC_REMOVE_FILTER_BUTTON        1063
#define IDC_CHECK1                      1063
#define IDC_SIMPLE_FILTER_DISABLED_CHECK 1063
#define IDC_SHOW_ID_IN_TREE             1063
#define IDC_NEW_WORD_CHECK              1063
#define IDC_NO_FILTERS                  1064
#define IDC_NO_FLTER_FRAME              1065
#define IDC_WORD_TEMPLATE_COMBO         1066
#define IDC_WORD_TEMPLATE_EDIT          1066
#define IDC_TREE_HAS_BUTTONS            1067
#define IDC_TREE_HAS_LINES              1068
#define IDC_IGNORE_RADIO                1069
#define IDC_DELETE_RADIO                1070
#define IDC_SET_DEFAULT_RADIO           1071
#define IDC_TEMPLATES_REFRESH_BUTTON    1072
#define IDC_TEMPLATE_BROWSE_BOTTON      1072
#define ID_MMGENREP                     32771
#define ID_MMSOURCES                    32772
#define ID_ELEMENT_EDIT                 32780
#define ID_MMDELETE                     32782
#define ID_FILE_OPTIONS                 32787
#define ID_OPEN_WORD_EDITOR             32788
#define ID_VIEW_STATICELEMENTTOOLBAR    32789
#define ID_VIEW_ACTIVEELEMENTTOOLBAR    32790
#define ID_BUTTON32791                  32791
#define ID_VIEW_STATICELEMENTSTOOLBAR   32792
#define ID_HLP_TOPICS                   32793
#define ID_SHOW_XML                     32794
#define ID_SIGN_ORPHANS                 32796
#define ID_DELETE_ORPHANS               32798
#define ID_RESET_ORPHANS                32800
#define ID_WORD_EDITOR_EDIT_ACTIVE_ELEMENT 32801
#define ID_MMNEWSTATICFIRST             39001
#define ID_MMNEWSTATICLAST              39009
#define ID_MMNEWACTIVEFIRST             39010
#define ID_MMNEWACTIVELAST              39100
#define IDS_INSERT_NEW_ELEMENT_WRONG_LOCATION 61205
#define IDS_SIMPLE_FILTER_FAILED_SOURCE_LOAD 61206
#define IDS_WB_WORD_LOADER_NOT_REGISTRED 61207
#define IDS_REFRESH_EL_ATTRIBUTES_FAILED 61209
#define IDS_ELEMENT_ATTRIBUTES_FAILED_LOAD 61210
#define IDS_DUPLICATE_ELEMENT_ID        61211
#define IDS_INVALID_ELEMENT_ID          61212
#define IDS_FAILED_CREATE_XML_DOM_INSTANCE 61213
#define IDS_CREATE_NEW_FILE_FAILED      61214
#define IDS_OPEN_FILE_FAILED            61215
#define IDS_AEL_TRANSFORTION_LOAD_FAILED 61216
#define IDS_AEL_LOAD_FAILED             61217
#define IDS_TR_OPTIONS_ERROR            61218
#define IDS_WRONG_ELEMENT_TRANSFORMATION 61219
#define IDS_AEL_NOFILTER                61220
#define IDS_INVALID_FILE_NAME           61221
#define IDS_STRING129                   61222
#define IDS_GENERATING_FAILED           61222
#define IDS_PUBLICID_DUPL               61223
#define IDS_DSLISTSAVE_ERR              61224
#define IDS_STRING61225                 61225
#define IDS_STYLLISTLOAD_ERR            61225
#define IDS_STYLLISTSAVE_ERR            61226
#define IDS_CONFIRM_THRAD_KILL          61400
#define IDS_CONFIRM_APP_RESUME          61401
#define IDS_COMPLEX_FILTER_SELECT_ATTR  61402
#define IDS_TOO_MANY_SELECTED_TRANSFORMATIONS 61403
#define IDS_TOO_MANY_SELECTED_ITEMS     61403
#define IDS_LACK_OF_GLOB_MEM_FOR_CLIPBOARD 61404
#define IDS_CLIPBOARD_USED_BY_OTHER_APP 61405
#define IDS_CLIPBOARD_WAS_NOT_EMPTIED   61406
#define IDS_CLIPBOARD_PLACE_DATA_ERROR  61407
#define IDS_NO_DATA_FROM_CLIPBOARD      61408
#define IDS_PARSE_ERROR                 61409
#define IDS_SETTINGS_ERR                61410
#define IDS_CLOSE_WORD_FIRST            61411

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1073
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
